version: "3.5"
services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/momo-backend:${CI_COMMIT_SHA}
    expose:
      - "8081"
    healthcheck:
      test: curl --fail -s http://localhost:8081/health
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - momo-store
    restart: always

  frontend:
    image: ${CI_REGISTRY_IMAGE}/momo-frontend:${CI_COMMIT_SHA}
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - momo-store
    restart: always

networks:
  sausage-store:
    name: momo-store
