host: "momo-store.mooo.com"
paths:
# - path: /app/
#   pathType: Prefix
#   backend:
#     service:
#       name: frontend
#       port:
#         number: 80
- path: /
  pathType: Prefix
  backend:
    service:
      name: prometheus-grafana
      port:
        number: 80