stages:
  - release
  - deploy

release-to-nexus:
  stage: release
  image: alpine/helm:3.9.3
  script:
    - cd infrastructure/momo-store-helm
    - helm package --dependency-update .
    - curl -u $NEXUS_USER:$NEXUS_PASS $NEXUS_HELM_REPO --upload-file *.tgz

deploy-to-kubernetes:
  stage: deploy
  image: alpine/helm:3.9.3
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - apk add jq
  script:
    - export BACKEND_VERSION=$(helm get values momo-backend -o json | jq .image.tag)
    - export FRONTEND_VERSION=$(helm get values momo-backend -o json | jq .image.tag)
    - cd infrastructure/momo-store-helm
    - helm upgrade --install --atomic momo-store . --set backend.image.tag=$BACKEND_VERSION --set frontend.image.tag=$FRONTEND_VERSION
    - rm ~/.kube/config
  environment:
    name: momo-store
    url: https://momo-store.mooo.com/
