# backend and frontend subchart
global:
  repo: gitlab.praktikum-services.ru:5050/antona-zateyev/momo-store/
  imagePullPolicy: Always
  revisionHistoryLimit: 15
  dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIllXNTBiMjVoTFhwaGRHVjVaWFk2TlVnNVN5RXFkR289IgoJCX0KCX0KfQ==

# cert-manager subchart
cert-manager:
  namespace: momo-store
  installCRDs: true

# prometheus-community/kube-prometheus-stack subchart
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      scrapeInterval: 10s
      scrapeTimeout: 10s
      additionalScrapeConfigs:
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
              - momo-store
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            regex: (.+);(.+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name