# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret-frontend
data:
  .dockerconfigjson: >-
    {{ .Values.global.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson